# Generated by Django 2.2.2 on 2019-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Address')),
                ('mobile_num_1', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile number 1')),
                ('mobile_num_2', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile number 2')),
                ('personal_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal mail')),
                ('email_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Office Email')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency contact person name')),
                ('emergency_contact_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Emergency contact person number')),
                ('joined_date', models.CharField(blank=True, max_length=12, null=True, verbose_name='Joined date')),
                ('joining_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Joining position')),
                ('bank_acc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank account number')),
            ],
        ),
    ]
